name: MLOps CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Code (flake8)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Unit Tests (pytest)
        run: |
          pip install pytest
          pytest -v --maxfail=2 --disable-warnings

  docker-build-test:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (Test Only)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            house-price-model:test

      - name: Run Container Sanity Test
        run: |
          docker run -d --name test-container -p 8501:8501 house-price-model:test
          echo "Waiting for container startup..."
          sleep 10
          docker ps -a
          docker logs test-container || true
          docker stop test-container
          docker rm test-container
